using Markdig;
using Markdig.Extensions.Yaml;
using Markdig.Syntax;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using VYaml.Annotations;
using VYaml.Serialization;

namespace Blog.Generator;

[Generator(LanguageNames.CSharp)]
public partial class Generator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var mdFilesSource = context.AdditionalTextsProvider
            .Where(t => t.Path.EndsWith(".md"))
            .Select((t, token) => new MarkdownFile(t.Path, t.GetText(token)))
            .Collect();

        context.RegisterSourceOutput(mdFilesSource, Emit);
    }

    private void Emit(SourceProductionContext context, ImmutableArray<MarkdownFile> source)
    {
        var posts = new Dictionary<string, List<MarkdownFile>>();
        foreach(var mdFile in source.Where(m => !m.FileName.Equals("Profile")))
        {
            var key = mdFile.FileName.AsSpan().Slice(0, 4).ToString();
            if (posts.TryGetValue(key, out var result))
            {
                result.Add(mdFile);
            }
            else
            {
                var mdFiles = new List<MarkdownFile>();
                mdFiles.Add(mdFile);
                posts[key] = mdFiles;
            }
        }

        var allPostEmitter = new StringBuilder();
        allPostEmitter.AppendLine("    public static readonly ImmutableArray<ImmutableArray<Post>> AllPost = [");
        foreach(var key in posts.Keys.OrderByDescending(k => k))
        {
            allPostEmitter.AppendLine($"        _{key},");
        }
        allPostEmitter.AppendLine("    ];");


        var postListEmitter = new StringBuilder();
        foreach (var p in posts.OrderByDescending(p => p.Key))
        {
            var postList = new StringBuilder();
            postList.AppendLine($"    public static readonly ImmutableArray<Post> _{p.Key} = [");
            foreach (var mdFile in p.Value.OrderByDescending(m => m.FileName))
            {
                if (mdFile.SourceText is null)
                {
                    continue;
                }

                var title = mdFile.Header.title;
                var date = mdFile.FileName;
                postList.AppendLine($"        new Post() {{ Title = \"{title}\", Date = \"{date}\", }},");
            }
            postList.AppendLine("    ];");
            postListEmitter.AppendLine(postList.ToString());
        }

        var code = $$"""
// <auto-generated> This .cs file is generated by CsToml.Generator. </auto-generated>
#nullable enable
#pragma warning disable CS0219 // The variable 'variable' is assigned but its value is never used
#pragma warning disable CS8600 // Converting null literal or possible null value to non-nullable type.
#pragma warning disable CS8601 // Possible null reference assignment.
#pragma warning disable CS8602 // Dereference of a possibly null reference.
#pragma warning disable CS8603 // Possible null reference return.
#pragma warning disable CS8604 // Possible null reference argument for parameter.
#pragma warning disable CS8619 // Possible null reference assignment fix

using System.Collections.Immutable;

namespace Blog;

public static class PostProvider
{
{{postListEmitter}}

{{allPostEmitter}}
}

public record struct Post
{
    public required string? Date { get; init; }

    public required string? Title { get; init; }
}
""";

        context.AddSource($"MarkdownFiles_generated.g.cs", code);
    }
}



public sealed record MarkdownFile
{
    private static readonly MarkdownPipeline markdownPipeline = new MarkdownPipelineBuilder()
        .UseAdvancedExtensions()
        .UseYamlFrontMatter()
        .Build();

    public string Path { get; init; }

    public SourceText? SourceText { get; init; }

    public string FileName => System.IO.Path.GetFileNameWithoutExtension(Path);

    public Header Header { get; init; }

    public MarkdownFile(string path, SourceText? sourceText)
    {
        Path = path;
        SourceText = sourceText;

        var markdown = SourceText?.ToString() ?? string.Empty;
        var document = Markdown.Parse(markdown, markdownPipeline);
        var yamlBlock = document.Descendants<YamlFrontMatterBlock>().FirstOrDefault();
        var yaml = markdown.Substring(yamlBlock.Span.Start, yamlBlock.Span.Length);

        Header = YamlSerializer.Deserialize<Header>(Encoding.UTF8.GetBytes(yaml));
    }
}

[YamlObject]
public partial class Header
{
    public string? title { get; set; }

    public string? url { get; set; }

    //public string? @namespace { get; set; }

}
